
from __future__ import annotations
from typing import Protocol, TypeVar, Callable, Optional, List
from uuid import UUID

T = TypeVar("T")

class IRepository(Protocol[T]):
    def add(self, entity: T) -> T: ...
    def get(self, id: UUID) -> Optional[T]: ...
    def get_all(self) -> List[T]: ...
    def update(self, entity: T) -> None: ...
    def delete(self, id: UUID) -> None: ...
    def find(self, predicate: Callable[[T], bool]) -> List[T]: ...
